# Complete CAPTCHA Configuration
# 完整的验证码系统配置文件

# ============================================================
# Dataset Generation Configuration
# 数据集生成配置
# ============================================================
dataset:
  # Input/Output paths
  paths:
    input_dir: 'data/raw'
    output_dir: 'data'
  
  # Parallel processing
  processing:
    max_workers: 24  # null for auto
    max_images: null   # null for all
    random_seed: null  # null for random
  
  # Dataset scale
  scale:
    min_backgrounds: 2000
    captchas_per_image: 100  # Number of CAPTCHAs to generate per background image
  
  # Confusion strategy distribution
  confusion_counts:
    none: 30
    rotation: 10
    perlin_noise: 5
    highlight: 10
    confusing_gap: 20
    hollow_center: 5
    gap_edge_highlight: 10  # 缺口边缘高光混淆，每张图生成10张
    combined: 10  # 减少combined数量，保持总数100
  
  # Shape configuration
  shapes:
    special: ['circle', 'square', 'triangle', 'hexagon']
    normal_count: 6
  
  # Puzzle sizes
  puzzle_sizes:
    all_sizes: [46, 48, 50, 52, 54, 56, 58, 60, 62, 64]
    sizes_per_image: 4
  
  # Grid-based position generation
  # 网格化位置生成系统
  grid_positions:
    # Background gap positions
    gap_x_positions: 4      # 背景缺口x轴4个位置
    gap_y_positions: 3      # 背景缺口y轴3个位置
    # Total gap combinations: 4 * 3 = 12
    
    # Slider positions  
    slider_x_positions: 3   # 滑块x轴3个位置（固定在左侧）
    # Slider uses same y positions as gap
    # Total captcha combinations: 12 * 3 = 36
  
  # Save options
  save:
    full_image: false
    components: false
    component_format: 'png'
    masks: false
  
  # Rotation
  rotation:
    enabled: true
    max_angle: 1.8  # degrees

# ============================================================
# Size Confusion Configuration
# 尺寸混淆配置
# ============================================================
size_confusion:
  # Generation size range
  generation:
    min_size: [280, 140]  # [width, height]
    max_size: [480, 240]
    common_sizes:
      - [320, 160]
      - [360, 180]
      - [400, 200]
      - [384, 192]
    common_size_probability: 0.3
  
  # Target size (neural network input size)
  target_size: [512, 256]  # [width, height]
  
  # Padding configuration
  padding:
    color: [255, 255, 255]  # BGR format, white padding
    mode: 'center'  # center, top_left, bottom_right

# ============================================================
# Confusion Strategy Configuration
# 混淆策略配置
# ============================================================
confusion_strategies:
  # Perlin Noise
  perlin_noise:
    noise_strength:
      min: 0.2
      max: 0.5
    noise_scale: 0.1
  
  # Rotation
  rotation:
    rotation_angle:
      min: 0.5
      max: 1.5
  
  # Highlight
  highlight:
    base_lightness:
      min: 20
      max: 40
    edge_lightness:
      min: 40
      max: 60
    directional_lightness:
      min: 15
      max: 30
    outer_edge_lightness: 0
  
  # Confusing Gap
  confusing_gap:
    num_confusing_gaps: [1, 2]
    confusing_type: 'mixed'  # same_y, different_y, mixed
    rotation_range:
      min: 10
      max: 30
    scale_range:
      min: 0.8
      max: 1.2
  
  # Circular Confusing Gap (圆形专用混淆缺口)
  circular_confusing_gap:
    num_confusing_gaps: [1, 2]
    confusing_type: 'mixed'  # same_y, different_y, mixed
    enable_smart_scaling: true
    y_distance_threshold: 7  # Y轴距离阈值（像素）
    scale_ranges:  # 智能缩放范围（当Y轴距离≤7px时使用）
      - [0.8, 0.9]  # 缩小范围
      - [1.1, 1.2]  # 放大范围
    normal_scale_range:  # 常规缩放范围（当Y轴距离>7px时使用）
      min: 0.8
      max: 1.2
  
  # Hollow Center
  hollow_center:
    scale:
      min: 0.3
      max: 0.4
  
  # Gap Edge Highlight (缺口边缘高光)
  gap_edge_highlight:
    edge_lightness:
      min: 90     # 边缘亮度最小值（0-100）
      max: 100     # 边缘亮度最大值（0-100）
    edge_width:
      min: 6      # 边缘宽度最小值（像素）
      max: 7      # 边缘宽度最大值（像素）
    decay_factor:
      min: 2.0    # 衰减系数最小值
      max: 2.5    # 衰减系数最大值
  
  # Combined
  combined:
    num_strategies: [2, 3]
    available_strategies:
      - 'perlin_noise'
      - 'rotation'
      - 'highlight'
      # - 'hollow_center'  # 从组合策略中移除，确保精确控制数量为5个
      - 'confusing_gap'
      - 'gap_edge_highlight'  # 添加到组合策略可用列表

# ============================================================
# Lighting Effects Configuration
# 光照效果配置
# ============================================================
lighting_effects:
  gap_shadow:
    base_darkness: 40
    edge_darkness: 50
    directional_darkness: 20
  
  gap_highlight:
    base_lightness: 30
    edge_lightness: 45
    directional_lightness: 20
    outer_edge_lightness: 0

# ============================================================