# Loss Function Configuration
# Stage7 Loss Configuration for Slider CAPTCHA Solver

# Focal Loss Configuration (CenterNet-style heatmap loss)
focal_loss:
  alpha: 1.5          # Focusing parameter for positive samples
  beta: 4.0           # Distance weighting parameter for negative samples
  pos_threshold: 0.8  # Threshold for positive samples (adjust based on Gaussian peak)
  eps: 1.0e-8        # Numerical stability constant

# Offset Loss Configuration (Sub-pixel regression)
offset_loss:
  beta: 1.0                # Smooth L1 beta parameter

# Hard Negative Loss Configuration (False gap suppression)
hard_negative_loss:
  margin: 0.5              # Margin for ranking loss (提高到0.5以更好地区分真假缺口)
  reduction: mean          # Options: mean, sum

# Angle Loss Configuration (Micro-rotation prediction)
angle_loss:
  pos_threshold: 0.7       # Threshold for supervision region (M_ang = 1(Y_gap > 0.7))
  eps: 1.0e-8              # Small constant to prevent division by zero

# Padding BCE Loss Configuration (Padding region suppression)
padding_bce_loss:
  enabled: true            # Enable padding BCE loss
  eps: 1.0e-8             # Numerical stability constant
  max_loss_per_pixel: 10.0 # Maximum loss per pixel to prevent gradient explosion

# Y-Axis Loss Configuration (Different y-axis enforcement)
y_axis_loss:
  enabled: true            # Enable y-axis loss
  tau: 1.0                # Softmax temperature parameter
  eps: 1.0e-8             # Numerical stability constant
  log_stretch: true       # Apply log stretching to row energies
  row_ce_weight: 1.0      # Weight for row classification loss
  emd_weight: 0.3         # Weight for EMD loss (0.2~0.5 recommended)

# Total Loss Configuration
total_loss:
  # Loss weights (λ in the formula)
  weights:
    heatmap: 1.0         # Weight for heatmap losses (gap + piece)
    offset: 1.0          # Weight for offset loss (λ=1.0 from documentation)
    hard_negative: 1.5   # Weight for hard negative loss (提高到1.5以强化假缺口抑制)
    angle: 0.5           # Weight for angle loss
    padding_bce: 0.3     # Weight for padding BCE loss
    y_axis: 0.8          # Weight for y-axis loss (确保不同y轴)
  
  # Feature flags
  use_angle: true            # Enable angle loss (for rotated gaps) - 必须启用以处理旋转混淆
  use_hard_negative: true    # Enable hard negative loss (for confusing gaps)
  
  # Advanced options
  loss_class: total          # Options: total, adaptive_total
  weight_schedule: constant  # Options: constant, linear, cosine (for adaptive)
  balance_losses: false      # Auto-balance loss magnitudes (for adaptive)

# Model-specific configurations for different stages
stage_configs:
  stage7:
    focal_loss:
      alpha: 1.5
      beta: 4.0
      pos_threshold: 0.8
      eps: 1.0e-8
    offset_loss:
      beta: 1.0
    hard_negative_loss:
      margin: 0.5          # 提高margin以更好地区分真假缺口
      reduction: mean
    angle_loss:
      pos_threshold: 0.7
      eps: 1.0e-8
    total_loss:
      weights:
        heatmap: 1.0
        offset: 1.0
        hard_negative: 1.5    # 提高权重以强化假缺口抑制
        angle: 0.5
        padding_bce: 0.3      # Padding BCE损失权重
      use_angle: true
