# Model Configuration
# 模型配置文件 - 集中管理神经网络和预处理的所有参数

# ============== 预处理配置 ==============
preprocessing:
  # Letterbox变换配置
  letterbox:
    # 目标尺寸从captcha_config.yaml的size_confusion.target_size读取
    # padding填充值 (0-255)
    fill_value: 255
    # 插值方法: linear, cubic, nearest, area
    interpolation: 'linear'
    
  # 坐标系统配置
  coordinate:
    # 下采样率 (用于生成1/4分辨率特征图)
    downsample: 4
    # 原始输入尺寸将从实际图像动态获取
    # 栅格尺寸会自动计算: (target_height/downsample, target_width/downsample)
    
  # 热图生成配置
  heatmap:
    # 高斯标准差 (栅格单位)
    sigma: 1.5
    # 正样本阈值 (用于确定监督区域)
    threshold: 0.7
    # 高斯半径因子 (radius = sigma * radius_factor)
    radius_factor: 3
    
  # Padding mask配置
  padding_mask:
    # padding区域的值
    padding_value: 1
    # 有效区域的值
    valid_value: 0
    # 下采样方法: avg (软屏蔽) 或 max (硬屏蔽)
    pooling_method: 'avg'
    
  # 角度处理配置
  angle:
    # 是否启用角度处理
    enabled: true
    # 最大旋转角度 (度)
    max_rotation: 1.8
    # 角度监督的热图阈值
    supervision_threshold: 0.7
    
  # 归一化配置
  normalization:
    # 是否启用归一化
    enabled: true
    # RGB均值 (ImageNet标准)
    mean: [0.485, 0.456, 0.406]
    # RGB标准差 (ImageNet标准)
    std: [0.229, 0.224, 0.225]

# ============== 输入配置 ==============
input:
  # 网络输入通道配置
  channels:
    grayscale: 1    # 灰度图通道数
    padding: 1      # Padding掩码通道
    total: 2        # 总输入通道数 (Grayscale + padding_mask)
  
  # PyTorch张量格式 [channels, height, width]
  # 会根据captcha_config.yaml中的size_confusion.target_size自动计算
  tensor_shape: [2, 256, 512]  # [C, H, W]

# ============== 网络架构配置 ==============
backbone:
  type: "Lite-HRNet-18"
  
  # Lite-HRNet配置
  lite_hrnet:
    # Stem (Stage1) - 特征提取阶段
    stem:
      in_channels: 2        # 输入通道数 (Grayscale + padding_mask)
      out_channels: 32      # 输出通道数
      expansion: 2          # LiteBlock扩张倍率
      
    # Stage2配置
    stage2:
      # 通道配置 - 决定模型容量
      channels: [32, 64]  # [1/4分辨率, 1/8分辨率]
      # 块数量配置 - 决定深度
      num_blocks: [2, 2]  # 每个分支的LiteBlock数量
      # 扩张倍率 - 影响参数量
      expansion: 2
      
    # Stage3配置
    stage3:
      # 通道配置 - 决定模型容量
      channels: [32, 64, 128]  # [1/4分辨率, 1/8分辨率, 1/16分辨率]
      # 块数量配置 - 决定深度
      num_blocks: [3, 3, 3]  # 每个分支的LiteBlock数量
      # 扩张倍率 - 影响参数量
      expansion: 2
      
    # Stage4配置
    stage4:
      # 通道配置 - 决定模型容量
      channels: [32, 64, 128, 256]  # [1/4, 1/8, 1/16, 1/32分辨率]
      # 块数量配置 - 决定深度
      num_blocks: [2, 2, 2, 2]  # 每个分支的LiteBlock数量
      # 扩张倍率 - 影响参数量
      expansion: 2
      
    # Stage5配置 (LiteFPN)
    stage5_lite_fpn:
      # 输入通道配置（来自Stage4的四个分支）
      in_channels: [32, 64, 128, 256]  # [1/4, 1/8, 1/16, 1/32分辨率]
      # FPN统一通道数
      fpn_channels: 128
      # 融合类型: 'add' (直接相加), 'weighted' (可学习权重), 'attention' (通道注意力)
      fusion_type: 'weighted'
      # 是否返回中间金字塔特征（用于辅助监督）
      return_pyramid: false
      
    # Stage6配置 (双头预测网络)
    stage6_dual_head:
      # 输入通道数（来自Stage5 LiteFPN的Hf）
      in_channels: 128
      # 中间层通道数
      mid_channels: 64
      # 是否使用角度预测头（用于处理微旋转）
      use_angle: true
      # 是否使用tanh限制偏移范围到[-0.5, 0.5]
      use_tanh_offset: true
      
  # 输出分辨率 (相对于输入)
  output_scales: [1/4, 1/8, 1/16, 1/32]