# Model Configuration
# 模型配置文件 - 集中管理神经网络的所有参数

# 输入配置
input:
  # 目标输入尺寸 (width, height) - 与size_confusion_config.py保持一致
  target_size: [512, 256]
  
  # PyTorch张量格式 (channels, height, width)
  tensor_shape: [3, 256, 512]
  
  # 输入通道配置
  channels:
    rgb: 3          # RGB通道数
    coord: 2        # 坐标编码通道
    padding: 1      # Padding掩码通道
    total: 6        # 总输入通道数

# 骨干网络配置
backbone:
  type: "HRNet"
  stages:
    - channels: 64
      resolution: [64, 128]   # (H, W)
    - channels: 128
      resolution: [32, 64]
    - channels: 256
      resolution: [16, 32]
    - channels: 512
      resolution: [8, 16]

# FPN-PAN配置
fpn_pan:
  in_channels: [64, 128, 256, 512]
  out_channels: 256
  
# Proposal生成配置
proposal:
  strides: [4, 8, 16, 32]
  top_k: 100
  
# ROI配置
roi:
  region:
    output_size: 64
    spatial_scale: 0.25   # 对应1/4分辨率
  shape:
    output_size: 64
    spatial_scale: 1.0    # 对应全分辨率

# SE2变换器配置
se2_transformer:
  d_model: 256
  n_heads: 8
  n_layers: 3
  dropout: 0.1

# 训练配置
training:
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  
# 推理配置
inference:
  # 坐标缩放因子 (从特征图到原始图像)
  coord_scale: 4
  
  # 置信度阈值
  confidence_threshold: 0.5
  
  # NMS阈值
  nms_threshold: 0.3

# 数据预处理配置 (训练/推理前的图像处理)
preprocessing:
  # Padding配置 (将不同尺寸图像统一到目标尺寸)
  padding:
    mode: 'letterbox'         # letterbox模式保持宽高比
    color: [0, 0, 0]          # RGB黑色填充
    
  # 归一化配置
  normalization:
    mean: [0.485, 0.456, 0.406]  # ImageNet均值
    std: [0.229, 0.224, 0.225]   # ImageNet标准差

# 数据增强配置 (训练时的额外增强)
augmentation:
  # 是否使用letterbox
  use_letterbox: true
  
  # 是否保持长宽比
  keep_aspect_ratio: true
  
  # 训练时的其他增强
  random_flip: false      # 滑块验证码不应翻转
  random_rotation: false  # 旋转已在生成时处理
  color_jitter: false     # 颜色扰动可能影响识别