# 预处理配置文件
# 用于验证码数据集的预处理和标准化

preprocessing:
  # Letterbox变换配置
  letterbox:
    target_size: [512, 256]  # [宽, 高] - 网络输入的固定尺寸
    fill_value: 255          # 填充值（白色）
    
  # 坐标映射配置  
  coordinate:
    downsample: 4            # 下采样率（特征图是输入的1/4）
    
  # 热图生成配置
  heatmap:
    sigma: 1.5               # 高斯分布标准差（栅格单位）
  
  # 图像量化配置
  quantization:
    enabled: true            # 是否启用量化
    bits_to_keep: 4          # 保留的高位数（4表示保留高4位，清除低4位）
    # 量化掩码会根据bits_to_keep自动计算
    # bits_to_keep=4 -> mask=0b11110000 (240)
    # bits_to_keep=5 -> mask=0b11111000 (248)
    # bits_to_keep=6 -> mask=0b11111100 (252)
      
# 数据集生成配置
dataset:
  batch_size: 64             # 批次大小，每批保存一个文件
  num_workers: 12            # 并行处理进程数（建议：CPU核心数的一半）
  chunk_size: 1              # 每个进程任务块大小，避免序列化开销
  maxtasksperchild: 10       # 每个进程处理任务数上限，防止内存累积
  gc_interval: 2             # 垃圾回收频率，每N批强制回收一次

# 路径配置（使用相对路径，相对于项目根目录）
paths:
  data_root: "./data"                      # 数据根目录
  output_dir: "./data/processed"           # 处理后数据输出目录
  labels_file: "./data/labels/all_labels.json"  # 标签文件路径

# 输出结构配置
output_structure:
  image_subdir: "images"     # 图像数据子目录
  label_subdir: "labels"     # 标签数据子目录
  split_info_subdir: "split_info"  # 数据集划分信息子目录
  
  # 数据集划分子目录（在image_subdir和label_subdir下）
  splits:
    train: "train"           # 训练集子目录
    val: "val"               # 验证集子目录
    test: "test"             # 测试集子目录

# 文件命名模板配置
file_naming:
  image_pattern: "{split}_{batch_id:04d}.npy"
  heatmap_pattern: "{split}_{batch_id:04d}_heatmaps.npy"
  offset_pattern: "{split}_{batch_id:04d}_offsets.npy"
  weight_pattern: "{split}_{batch_id:04d}_weights.npy"
  meta_pattern: "{split}_{batch_id:04d}_meta.json"
  index_pattern: "{split}_index.json"
  
# 输入输出维度（自动计算，无需修改）
dimensions:
  input_channels: 2          # Grayscale(1) + padding_mask(1)
  input_shape: [2, 256, 512] # [C, H, W]
  grid_size: [64, 128]       # [H/4, W/4] - 特征图尺寸
  heatmap_channels: 2        # gap + slider
  offset_channels: 4         # gap_x, gap_y, slider_x, slider_y

# 数据集划分配置
# Dataset split configuration
data_split:
  # 划分比例
  split_ratio:
    train: 0.8               # 80% 训练集
    val: 0.1                 # 10% 验证集
    test: 0.1                # 10% 测试集
  
  # 划分选项
  options:
    random_seed: 42          # 随机种子，保证可重现性
    stratify_by_image: true  # 按图片ID分层，防止数据泄漏
    shuffle: true            # 划分前打乱数据
    auto_split: true         # 是否自动划分数据集（默认true，会生成train/val/test）